#!/bin/bash

sudo apt install curl -y

# Install apt-fast
/bin/bash -c "$(curl -sL https://git.io/vokNn)"

# Install Git
sudo apt-fast -y install git-all

sudo apt-fast -y install build-essential rustc libssl-dev libyaml-dev zlib1g-dev libgmp-dev

# Install mise
curl https://mise.run | sh
echo 'eval "$(~/.local/bin/mise activate bash)"' >> ~/.bashrc

# Install PostgreSQL
sudo apt-fast install -y postgresql postgresql-common libpq-dev
sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh

# Install noti
curl -L $(curl -s https://api.github.com/repos/variadico/noti/releases/latest | awk '/browser_download_url/ { print $2 }' | grep 'linux-amd64' | sed 's/"//g') | tar -xz
sudo mv noti /usr/bin/noti

# Install Dropbox
cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -

# Clone dotfiles repo and create symlinks
git clone https://github.com/dngst/dotfiles.git
find ~/dotfiles -name ".*" -type f -exec ln -s {} ~ \;

# Install Vim
sudo apt build-dep -y vim
git clone https://github.com/vim/vim.git
cd vim/src && ./configure --with-x --disable-gui && make && sudo make install

# Install vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

sudo apt-fast install xclip ack-grep gvfs-backends redshift redshift-gtk -y

curl -fsS https://dl.brave.com/install.sh | sh

# Set Vim as default editor
echo "export EDITOR='/usr/local/bin/vim'" >> ~/.bashrc

mkdir ~/workspace

crontab ~/dotfiles/cronjobs.txt

cp ~/dotfiles/redshift.conf ~/.config
cp ~/dotfiles/xfce4-terminal.xml ~/.config/xfce4/xfconf/xfce-perchannel-xml

sudo -u postgres createuser --superuser $USER
sudo -u postgres createdb $USER

sudo apt update
sudo apt-fast upgrade -y
sudo apt autoremove

ssh-keygen -t ed25519 -C "dngst@protonmail.com"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519
xclip -selection c < ~/.ssh/id_ed25519.pub
