#!/bin/bash

# Install apt-fast
sudo add-apt-repository ppa:apt-fast/stable
sudo apt-get update
sudo apt-get -y install apt-fast

# Install Git
sudo apt-fast -y install git-all

# Install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
source ~/.bashrc

# Install Redis
sudo snap install redis

# Install ruby-build
git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build

# Install rbenv
sudo apt-fast install libssl-dev libreadline-dev zlib1g-dev autoconf bison build-essential libyaml-dev libreadline-dev libncurses5-dev libffi-dev libgdbm-dev
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
source ~/.bashrc

# Install PostgreSQL
sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update
sudo apt-fast -y install postgresql postgresql-contrib libpq-dev

sudo apt-fast install ubuntu-restricted-extras tlp tree -y

# Install Node.js
nvm install --lts

# Install noti
curl -L $(curl -s https://api.github.com/repos/variadico/noti/releases/latest | awk '/browser_download_url/ { print $2 }' | grep 'linux-amd64' | sed 's/"//g') | tar -xz
sudo mv noti /usr/bin/noti

git clone https://github.com/vim/vim.git
cd vim/src && make && sudo make install

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo '
if [ -f ~/.bash_aliases ]; then
     . ~/.bash_aliases
fi
' >> ~/.bashrc

mkdir ~/workspace

git clone https://github.com/dngst/dotfiles.git
find ~/dotfiles -name ".*" -type f -exec ln -s {} ~ \;

curl https://raw.githubusercontent.com/riobard/bash-powerline/master/bash-powerline.sh > ~/.bash-powerline.sh
echo 'source ~/.bash-powerline.sh' >> ~/.bashrc
source ~/.bashrc

# Update and clean
sudo apt-fast update && sudo apt-fast upgrade -y
sudo apt autoclean && sudo apt autoremove -y

sudo -u postgres createuser $USER
sudo -u postgres createdb $USER

